export default [
    {
        id: 1,
        title: "Learn wedding photography",
        description: "Explore our curated list of 27 top wedding photographers from around the world, showcasing diverse styles and exceptional talent in capturing love stories.",
        price: 125,
        coverImg: "https://picsum.photos/id/237/200/300",
        status: {
            rating: 5.0,
            reviewCount: 30,
        },
        location: "Online",
        openSpots: 0,
    },
    {
        id: 2,
        title: "Life lessons with Katie Zaferes",
        description: "The tips below will help you make the most of your (likely) first professional photographs with your future spouse. Couples, you may know your future spouse pretty well, but this is a first date with your photographer. Photographers, this is your chance to set the stage and build trust with your couples, so I have tips for you too.",
        price: 145,
        coverImg: "https://picsum.photos/seed/picsum/200/300",
        status: {
            rating: 5.0,
            reviewCount: 6,
        },
        location: "Online",
        openSpots: 99,
    },
    {
        id: 3,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "Norway",
        openSpots: 176,
    },
    {
        id: 4,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "USA",
        openSpots: 176,
    },
    {
        id: 5,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "USA",
        openSpots: 176,
    },
    {
        id: 6,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "USA",
        openSpots: 176,
    },
    {
        id: 7,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "USA",
        openSpots: 176,
    },
    {
        id: 8,
        title: "Group Mountain Biking",
        description: "Every photographer structures their engagement sessions a little differently, so you can always ask your photographer if there’s anything you need to know or look at their engagement photos to get an idea of what to expect.",
        price: 146,
        coverImg: "https://picsum.photos/200/300?grayscale",
        status: {
            rating: 4.8,
            reviewCount: 34,
        },
        location: "USA",
        openSpots: 176,
    },
]